version: 2

builds:
  - main: ./cmd/grove
    binary: grove
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "grove_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

homebrew_casks:
  - name: grove
    repository:
      owner: chrisbanes
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/AmpInc/grove"
    description: "Manage CoW-cloned workspaces with warm build caches"
    license: "MIT"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
