name: Feature Request
description: Suggest a new feature or enhancement for Grove
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for Grove? We'd love to hear it! Please describe what
        you'd like to see and why it would be useful.

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this feature solve? What workflow does it improve?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you envision this working? Include example commands or workflows if applicable.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative approaches or workarounds?
    validations:
      required: false

  - type: dropdown
    id: scope
    attributes:
      label: Area
      description: Which part of Grove does this relate to?
      options:
        - CLI commands
        - Configuration / hooks
        - Platform support (Linux, etc.)
        - AI agent integration
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, screenshots, or references.
    validations:
      required: false
